### ISSUE TITLE
Add, configure a slice of logic and set levels for the logger

### ISSUE THREAD

**Issue by satishusk** [ProkopovVsevolod/practic-site#4]
Logger levels:
```
logging:
  level:
    org.springframework.security: trace
    root: info
    com.finance.logger: debug
```
